apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot
  namespace: devopsproject
spec:
  selector:
    matchLabels:
      app: myspringbootapp
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
      containers:
      - name: mycontainer
        image: tharun13055/maven_dev:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
