apiVersion: v1
kind: Service
metadata:
  name: my-springboot-service
  namespace: devopsproject
  labels:
    app: myspringbootapp
spec:
  selector:
    app: myspringbootapp
  ports:
    - port: 80
      nodePort: 30036
      protocol: TCP
      targetPort: 9000
  type: LoadBalancer
  